version: "3.5"

services:
  postgres:
    image: postgres:15
    volumes:
      - ./db/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - '6379:6379'