version: '3.5'
services:
  api1: # API - Instância 01
    image: rinha-backend-kotlin
    hostname: api1
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/rinha
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2: # API - Instância 02
    image: rinha-backend-kotlin
    hostname: api2
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/rinha
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db: # Banco de dados
    image: postgres:15
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rinha"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
