version: "3.5"

services:
  postgres:
    image: postgres:15
    volumes:
      - ./db/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
  mysql:
    image: mysql:8
    volumes:
      - ./db/mysql/scripts:/docker-entrypoint-initdb.d
      - ./db/mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_USER: rinha
      MYSQL_PASSWORD: rinha
      MYSQL_DATABASE: rinha
      MYSQL_ROOT_PASSWORD: dev
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    ports:
      - '6379:6379'