version: '3.5'
services:
  api1: &api # API - Instância 01
    image: ghcr.io/faogustavo/rinha-de-backend-q3-2023-ktor:main
    hostname: api1
    depends_on:
      db:
        condition: service_healthy
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx512M -Xms512M -XX:+UseG1GC -XX:+AlwaysPreTouch -XX:MaxGCPauseMillis=50 -XX:InitiatingHeapOccupancyPercent=70"
      DATABASE_DRIVER: com.mysql.cj.jdbc.Driver
      DATABASE_URL: jdbc:mysql://localhost:3306/rinha
      MAX_POOL_SIZE: 240
      DISABLE_EXPOSED: "true"
      DISABLE_CACHE: "true"
      KTOR_ENGINE: Netty
      HTTP_PORT: 8081
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.75GB'
    network_mode: "host"

  api2: # API - Instância 02
    <<: *api
    hostname: api2
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx512M -Xms512M -XX:+UseG1GC -XX:+AlwaysPreTouch -XX:MaxGCPauseMillis=50 -XX:InitiatingHeapOccupancyPercent=70"
      DATABASE_DRIVER: com.mysql.cj.jdbc.Driver
      DATABASE_URL: jdbc:mysql://localhost:3306/rinha
      MAX_POOL_SIZE: 240
      DISABLE_EXPOSED: "true"
      DISABLE_CACHE: "true"
      KTOR_ENGINE: Netty
      HTTP_PORT: 8082

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ../../nginx-host.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.5GB'
    network_mode: "host"

  db:
    image: mysql:8
    volumes:
      - ../../db/mysql/scripts:/docker-entrypoint-initdb.d
      - ../../db/mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_USER: rinha
      MYSQL_PASSWORD: rinha
      MYSQL_DATABASE: rinha
      MYSQL_ROOT_PASSWORD: dev
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1GB'
    network_mode: "host"

